name: Build project

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: build-plugin
          gradle-distribution-sha-256-sum-warning: false

      - name: Code style check
        run: ./gradlew projectCodestyle --stacktrace

      - run: ./gradlew assemble --stacktrace

      - run: ./gradlew validatePlugins --stacktrace

      - run: ./gradlew projectCoverage --stacktrace

      - uses: codecov/codecov-action@v1

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: "${{ github.workspace }}/**/build/reports/tests"

      - name: Upload jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: "${{ github.workspace }}/**/build/reports/jacoco"

  build-all-sample-apps:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle: [ 6.5, 6.7.1, current, rc ]
        agp: [ 4.1.0, 4.2.0, 7.0.0-alpha15 ]
        exclude:
          - gradle: 6.5
            agp: 7.0.0-alpha15
          - gradle: 6.7.1
            agp: 7.0.0-alpha15
          - gradle: 6.5
            agp: 4.2.0

    name: Run Gradle-${{ matrix.gradle }}, AGP-${{ matrix.agp }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: build-all-sample-apps
          gradle-distribution-sha-256-sum-warning: false

      - name: Pre-compile plugin
        run: ./gradlew publishToMavenLocal -Pgroup=com.project.starter.local

      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: sample
          gradle-version: ${{ matrix.gradle }}
          dependencies-cache-enabled: true
          arguments: assemble lint -PuseMavenLocal -PagpVersion=${{ matrix.agp }} --stacktrace

  icons-test:
    runs-on: macos-latest
    strategy:
      matrix:
        apiVersion: [ 28 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: icons
          gradle-distribution-sha-256-sum-warning: false

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade Pillow

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.apiVersion }}
          profile: pixel_xl
          script: cd sample && ./icon_check.sh

      - name: Upload failed screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failedScreenshots
          path: "${{ github.workspace }}/**/build/failedScreenshots"

      - name: Upload screenshot tests result
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: "${{ github.workspace }}/**/build/*AndroidTest/"
