name: Build project

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v1.6
        with:
          job-id: build-plugin
      - name: Code style check
        run: ./gradlew projectCodestyle --stacktrace
      - name: Assemble
        run: ./gradlew assemble --stacktrace
      - name: Validate Plugins
        run: ./gradlew validatePlugins validateTaskProperties --stacktrace
      - name: Unit tests
        run: ./gradlew projectCoverage --stacktrace
      - uses: codecov/codecov-action@v1
      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: "${{ github.workspace }}/**/build/reports/tests"
      - name: Upload jacoco report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: "${{ github.workspace }}/**/build/reports/jacoco"

  build-all-sample-apps:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gradle: [ 6.1.1, current, rc ]
        agp: [ 4.0.0, 4.1.1 ]
        exclude:
          - gradle: 6.1.1
            agp: 4.1.1
    name: Run Gradle-${{ matrix.gradle }}, AGP-${{ matrix.agp }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v1.6
        with:
          job-id: build-all-sample-apps
      - name: Pre-compile plugin
        run: ./gradlew publishToMavenLocal -Pgroup=com.project.starter.local
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: sample
          gradle-version: ${{ matrix.gradle }}
          dependencies-cache-enabled: true
          arguments: projectCode -PuseMavenLocal -PagpVersion=${{ matrix.agp }} --stacktrace
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: sample
          gradle-version: ${{ matrix.gradle }}
          dependencies-cache-enabled: true
          arguments: assemble -PuseMavenLocal -PagpVersion=${{ matrix.agp }} --stacktrace

  icons-test:
    runs-on: macos-latest
    strategy:
      matrix:
        apiVersion: [ 28 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache .gradle
        uses: burrunan/gradle-cache-action@v1.6
        with:
          job-id: icons
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade Pillow
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.apiVersion }}
          profile: pixel_xl
          script: cd sample && ./icon_check.sh
      - name: Upload failed screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failedScreenshots
          path: "${{ github.workspace }}/**/build/failedScreenshots"
      - name: Upload screenshot tests result
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: "${{ github.workspace }}/**/build/*AndroidTest/"
