name: Publish Project to Gradle Plugin Portal

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Build app with Gradle
        run: ./gradlew build

      - name: Publish to Gradle Plugin Portal
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.gradle_publish_key }} -Pgradle.publish.secret=${{ secrets.gradle_publish_secret }}

      - name: Publish to Github Package Registry
        run: ./gradlew publish --continue || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
